name: CI - Smoke Reproducibility

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install pip packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run smoke script (toy data + 1-epoch alignment)
      run: |
        chmod +x run_smoke.sh || true
        ./run_smoke.sh

    - name: Upload alignment checkpoint
      uses: actions/upload-artifact@v4
      with:
        name: alignment-final
        path: ./checkpoints/alignment/final_aligned.pt
